server {
    listen 127.0.0.1:8080 ;
    server_name "example.com" ;
    # default_error_page 404 "/html" ;
    location / {
        root "/home/bramzil/mini-server/" ;
        # index "/core/Core.hpp" ;
        # auto_index oN ;
        allowed_method GET ;
        # index "index.html" ;
        # cookie_to_set user=brahim; HttpOnly ;
        # cookie_to_set sessionId=brahim; HttpOnly ;
        # cookie_to_set path=html; HttpOnly ;
        cgi_application ".php" "/usr/bin/php-cgi" ;
        cgi_application ".py" "/usr/bin/python3" ;
        # redirect_to 300 "hello" ;
    }

    # location html {
    #     root "/home/bramzil/mini-server/www" ;
    #     allowed_method POST  GET ;
    #     # cgi_application ".php" "/usr/bin/php-cgi" ;
    # }
}

# server {
#     listen 127.0.0.1:9090 ;
#     server_name "example.com" ;
#     location /includes {
#         allowed_method GET ;
#         root "/home/bramzil/mini-server" ;
#     }
# }